# DOCKER-VERSION 1.1.0

#inherit from the base container, which have all the needed script to launch tasks
ARG   VERSION=latest
FROM  akemery/inginious-c-base-webtop:${VERSION}
LABEL org.inginious.grading.name="default"
